Modifications to Harfbuzz 7.0.1
hb-subset.cc has the include for hb-ot-name-language-static.hh
commented out since it's also included in hb-ot-name.cc which results in
multiple definitions of the same functions.

In hb-algs.hh, __builtin_mul_overflow is not supported by xlc.

noexcept-type warnings are ignored when compiling with gcc 7.5 to avoid
errors like the following.
```
19:26:52  ./src/java.desktop/share/native/libharfbuzz/hb-iter.hh:676:3:
error: mangled name for 'hb_apply_t<Appl>::hb_apply_t(Appl) [with Appl =
void (&)(void*) throw ()]' will change in C++17 because the exception
specification is part of a function type [-Werror=noexcept-type]
19:26:52     hb_apply_t (Appl a) : a (a) {}
19:26:52     ^~~~~~~~~~

19:26:52  ./src/java.desktop/share/native/libharfbuzz/hb-iter.hh:680:8:
error: mangled name for 'void hb_apply_t<Appl>::operator()(Iter) [with
Iter = hb_array_t<hb_pool_t<hb_serialize_context_t::object_t>::chunk_t*
const>; typename hb_enable_if<hb_is_iterator_of<Iter, typename
Iter::item_t>::value>::type* <anonymous> = 0; Appl = void (&)(void*)
throw ()]' will change in C++17 because the exception specification is
part of a function type [-Werror=noexcept-type]
19:26:52     void operator () (Iter it)
19:26:52          ^~~~~~~~

```

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>